# Generated by Django 5.1.4 on 2025-01-12 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='shortlink_data',
            new_name='ShortlinkData',
        ),
    ]
