# Generated by Django 5.1.4 on 2025-01-12 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_shortlink_data_shortlinkdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortlinkdata',
            name='shorten_id',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
