# Generated by Django 5.1.1 on 2025-01-12 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_shortlinkdata_shorten_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShortlinkData',
        ),
    ]
