# Generated by Django 5.1.1 on 2025-01-12 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0004_delete_shortlinkdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinksData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('redirect_link', models.URLField()),
                ('short_id', models.CharField(max_length=10)),
            ],
        ),
    ]
